sudo: required
services:
  - docker

before_install:
  - docker build -t cyw233/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cyw233/react-test npm test -- --coverage

after_success:
  - docker build -t cyw233/multi-client ./client
  - docker build -t cyw233/multi-nginx ./nginx
  - docker build -t cyw233/multi-server ./server
  - docker build -t cyw233/multi-worker ./worker
  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push cyw233/multi-client
  - docker push cyw233/multi-nginx
  - docker push cyw233/multi-server
  - docker push cyw233/multi-worker